# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'chipper'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["chipper_left rgbled_adapter","chipper_right rgbled_adapter"]'
      modules: '["caksoylar/zmk-rgbled-widget/main"]'
