# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'chipper'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["chipper_left nice_view_adapter nice_epaper","chipper_right nice_view_adapter nice_epaper"]'
      modules: '["mctechnology17/zmk-nice-oled/main"]'
